import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import jsrConfig from "../../jsr.json" with { type: "json" };

interface Options {
	port: number;
	secret: string;
	output: string;
	imageTag: string;
}

function parseArgs(args: string[]): Options {
	const options: Options = {
		port: 8080,
		secret: "",
		output: "./docker-compose.sandbox.yml",
		imageTag: jsrConfig.version,
	};

	for (let i = 0; i < args.length; i++) {
		switch (args[i]) {
			case "--port":
				options.port = Number(args[++i]);
				if (Number.isNaN(options.port)) {
					console.error("Error: --port requires a numeric value.");
					process.exit(1);
				}
				break;
			case "--secret":
				options.secret = args[++i];
				break;
			case "--generate-secret":
				options.secret = randomBytes(16).toString("hex");
				break;
			case "--output":
				options.output = args[++i];
				break;
			case "--image-tag":
				options.imageTag = args[++i];
				break;
			case "--help":
			case "-h":
				console.log(`Usage: megasthenes setup-sandbox [options]

Generate a docker-compose file for the megasthenes sandbox server.

Options:
  --port <number>       Host port to expose (default: 8080)
  --secret <string>     Bearer token for sandbox API authentication
  --generate-secret     Generate a random 32-char hex secret
  --output <path>       Output file path (default: ./docker-compose.sandbox.yml)
  --image-tag <tag>     Container image tag (default: ${jsrConfig.version})
  --help, -h            Show this help message`);
				process.exit(0);
				break;
			default:
				console.error(`Unknown option: ${args[i]}\nRun 'megasthenes setup-sandbox --help' for usage.`);
				process.exit(1);
		}
	}

	return options;
}

function checkDocker(): boolean {
	const result = spawnSync("docker", ["--version"], { stdio: "pipe" });
	if (result.status !== 0) {
		console.error("Error: docker not found on PATH. Install Docker to use the sandbox.");
		return false;
	}
	return true;
}

function checkGvisor(): void {
	const result = spawnSync("docker", ["info", "--format", "{{json .Runtimes}}"], {
		stdio: "pipe",
	});
	const output = result.stdout?.toString() ?? "";
	if (!output.includes("runsc")) {
		console.warn(`Warning: gVisor runtime (runsc) not detected in Docker.
The sandbox requires gVisor for full isolation.
Install: https://gvisor.dev/docs/user_guide/install/
After installing, add to /etc/docker/daemon.json:
  { "runtimes": { "runsc": { "path": "/usr/local/bin/runsc" } } }
Then: sudo systemctl restart docker
`);
	}
}

function composeTemplate(options: Options): string {
	const secretEnv = options.secret ? `\n      - SANDBOX_SECRET=${options.secret}` : "";

	return `# Generated by: megasthenes setup-sandbox
# Sandbox worker for megasthenes — isolated git + tool execution.
# Requires gVisor runtime (runsc). See: https://gvisor.dev/docs/user_guide/install/

services:
  sandbox:
    image: ghcr.io/nilenso/megasthenes-sandbox:${options.imageTag}
    runtime: runsc
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp:rw,size=64m
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${options.port}:8080"
    environment:
      - PORT=8080${secretEnv}
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:8080/health').then(r=>r.ok?process.exit(0):process.exit(1)).catch(()=>process.exit(1))"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
`;
}

export async function setupSandbox(args: string[]): Promise<void> {
	const options = parseArgs(args);

	if (!checkDocker()) {
		process.exit(1);
	}
	checkGvisor();

	const outputPath = resolve(options.output);
	if (existsSync(outputPath)) {
		console.warn(`Warning: ${options.output} already exists and will be overwritten.`);
	}

	writeFileSync(outputPath, composeTemplate(options));

	const secretLine = options.secret ? `\n        secret: "${options.secret}",` : "";

	console.log(`Created ${options.output}

Start the sandbox:
  docker compose -f ${options.output} up -d

Use in your code:
  const client = new Client({
    sandbox: {
      baseUrl: "http://localhost:${options.port}",${secretLine}
    },
  });`);
}
